### ISSUE TITLE
Invocation of app with `--conn_type=serial` argument fails

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture_App#1049]
Ran the app the following way: `python main.py -- --conn_type=serial`.  Output is below:
```
(fedora_env) [stieg@lucious app]$ python main.py -- --conn_type=serial
[INFO              ] [Logger      ] Record log in /home/stieg/.kivy/logs/kivy_16-07-11_10.txt
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v2.7.11 (default, Jun 21 2016, 09:15:12)
[GCC 6.1.1 20160510 (Red Hat 6.1.1-2)]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_pygame, img_pil (img_ffpyplayer ignored)
[INFO              ] [Window      ] Provider: pygame(['window_egl_rpi'] ignored)
[INFO              ] [GL          ] OpenGL version <3.0 Mesa 11.2.2 (git-5de088f)>
[INFO              ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
[INFO              ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Ivybridge Mobile >
[INFO              ] [GL          ] OpenGL parsed version: 3, 0
[INFO              ] [GL          ] Shading version <1.30>
[INFO              ] [GL          ] Texture max size <8192>
[INFO              ] [GL          ] Texture max units <16>
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
 /home/stieg/Devel/asl/app/fedora_env/lib/python2.7/site-packages/kivy/core/clipboard/clipboard_gtk3.py:14: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
   from gi.repository import Gtk, Gdk
[INFO              ] [Clipboard   ] Provider: gtk3(['clipboard_dbusklipper'] ignored)
xclip version 0.12
Copyright (C) 2001-2008 Kim Saunders et al.
Distributed under the terms of the GNU GPL
[INFO              ] [Cutbuffer   ] Provider: xclip
[INFO              ] [CutBuffer   ] cut buffer support enabled
[INFO              ] [Text        ] Provider: pygame
[WARNING           ] Call to deprecated function __call__ in /home/stieg/Devel/asl/app/fedora_env/lib/python2.7/site-packages/kivy/utils.py line 402.Called from /home/stieg/Devel/asl/app/autosportlabs/widgets/filebrowser/__init__.py line 82 by <module>().
[WARNING           ] Call to deprecated function __call__ in /home/stieg/Devel/asl/app/fedora_env/lib/python2.7/site-packages/kivy/utils.py line 402.Called from /home/stieg/Devel/asl/app/autosportlabs/racecapture/settings/systemsettings.py line 42 by get_default_data_dir().
[WARNING           ] Call to deprecated function __call__ in /home/stieg/Devel/asl/app/fedora_env/lib/python2.7/site-packages/kivy/utils.py line 402.Called from /home/stieg/Devel/asl/app/autosportlabs/racecapture/settings/systemsettings.py line 51 by get_default_user_files_dir().
[WARNING           ] Call to deprecated function __call__ in /home/stieg/Devel/asl/app/fedora_env/lib/python2.7/site-packages/kivy/utils.py line 402.Called from /home/stieg/Devel/asl/app/autosportlabs/racecapture/settings/systemsettings.py line 59 by get_default_desktop_config_dir().
[INFO              ] [UserPrefs   ] Data Dir is: /home/stieg/.config/racecapture
[INFO              ] [AppConfig   ] using user storage directory: /home/stieg/.config/racecapture
[INFO              ] [GL          ] NPOT texture support is available
[INFO              ] [OSC         ] using <multiprocessing> for socket
[INFO              ] [Base        ] Start application main loop
[INFO              ] [RacecaptureApp] initializing rc comms with, conn type: serial
[INFO              ] [RCPAPI      ] msg_rx_worker starting
[INFO              ] [RCPAPI      ] cmd_sequence_worker starting
[CRITICAL          ] [CrashHandler] Caught exception in Kivy loop: 'NoneType' object has no attribute 'CONNECT_TIMEOUT'
[INFO              ] [RCPAPI      ] auto_detect_worker starting
[WARNING           ] [RCPAPI      ] Message rx worker exception: None | <type 'exceptions.Exception'>
[CRITICAL          ] [Traceback (most recent call last)]
  File "/home/stieg/Devel/asl/app/fedora_env/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 403, in mainloop
    self._mainloop()
  File "/home/stieg/Devel/asl/app/fedora_env/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 290, in _mainloop
    EventLoop.idle()
  File "/home/stieg/Devel/asl/app/fedora_env/lib/python2.7/site-packages/kivy/base.py", line 327, in idle
    Clock.tick()
  File "/home/stieg/Devel/asl/app/fedora_env/lib/python2.7/site-packages/kivy/clock.py", line 515, in tick
    self._process_events()
  File "/home/stieg/Devel/asl/app/fedora_env/lib/python2.7/site-packages/kivy/clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "/home/stieg/Devel/asl/app/fedora_env/lib/python2.7/site-packages/kivy/clock.py", line 406, in tick
    ret = callback(self._dt)
  File "main.py", line 370, in <lambda>
    Clock.schedule_once(lambda dt: self.init_rc_comms())
  File "main.py", line 404, in init_rc_comms
    rc_api.run_auto_detect()
  File "/home/stieg/Devel/asl/app/autosportlabs/racecapture/api/rcpapi.py", line 145, in run_auto_detect
    self.msg_rx_timeout = self.comms.CONNECT_TIMEOUT
AttributeError: 'NoneType' object has no attribute 'CONNECT_TIMEOUT'
```

Wonder if the serial type is not there or is simply not populated correctly.

(fedora_env) [stieg@lucious app]$ git describe --always --dirty
v1.6.0-64-gddafada

**Comment by ryandoherty** [comment]
Fixed in https://github.com/autosportlabs/RaceCapture_App/commit/2f27fd4d98409d058c97f0b7bf011eee950fd14e
