### ISSUE TITLE
ValueError: <autosportlabs.racecapture.config.rcpconfig.AnalogChannel object at 0x7fa2b7c76790> is not in list

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture_App#1106]
Hit the following stack trace while loading up the RCT config over WiFi.  It hesitated a couple of times, then successfully loaded the config only to hit this value error:

```
[INFO              ] [SessionRecorder] stopping session
[CRITICAL          ] [Clock       ] Warning, too much iteration done before the next frame. Check your code, or increase the Clock.max_iteration attribute
[WARNING           ] [RCPAPI      ] Read message timeout waiting for capabilities
[WARNING           ] [RCPAPI      ] POKE
[WARNING           ] [RCPAPI      ] Read message timeout waiting for capabilities
[WARNING           ] [RCPAPI      ] POKE
[WARNING           ] [RCPAPI      ] Level 2 retry for (0) capabilities
[INFO              ] [LinksCapabilities] {'cellular': True, 'bluetooth': True}
[WARNING           ] [RCPAPI      ] Read message timeout waiting for lapCfg
[WARNING           ] [RCPAPI      ] POKE
[WARNING           ] [RCPAPI      ] Read message timeout waiting for lapCfg
[WARNING           ] [RCPAPI      ] POKE
[WARNING           ] [RCPAPI      ] Level 2 retry for (0) lapCfg
[INFO              ] [LinksCapabilities] {'cellular': True, 'bluetooth': True}
[INFO              ] [RcpConfig   ] Config version 2.10.0 Loaded
[CRITICAL          ] [CrashHandler] Caught exception in Kivy loop: <autosportlabs.racecapture.config.rcpconfig.AnalogChannel object at 0x7fa2b7c76790> is not in list
[CRITICAL          ] [Traceback (most recent call last)]
  File "/home/stieg/Devel/asl/app/fedora_env/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 403, in mainloop
    self._mainloop()
  File "/home/stieg/Devel/asl/app/fedora_env/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 290, in _mainloop
    EventLoop.idle()
  File "/home/stieg/Devel/asl/app/fedora_env/lib/python2.7/site-packages/kivy/base.py", line 327, in idle
    Clock.tick()
  File "/home/stieg/Devel/asl/app/fedora_env/lib/python2.7/site-packages/kivy/clock.py", line 515, in tick
    self._process_events()
  File "/home/stieg/Devel/asl/app/fedora_env/lib/python2.7/site-packages/kivy/clock.py", line 647, in _process_events
    event.tick(self._last_tick, remove)
  File "/home/stieg/Devel/asl/app/fedora_env/lib/python2.7/site-packages/kivy/clock.py", line 406, in tick
    ret = callback(self._dt)
  File "./main.py", line 248, in <lambda>
    Clock.schedule_once(lambda dt, inner_listener=listener: inner_listener.dispatch('on_config_updated', self.rc_config))
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-JdAJot/kivy/kivy/_event.c:7699)
  File "/home/stieg/Devel/asl/app/autosportlabs/racecapture/views/configuration/rcp/configview.py", line 114, in on_config_updated
    self.update_config_views()
  File "/home/stieg/Devel/asl/app/autosportlabs/racecapture/views/configuration/rcp/configview.py", line 147, in update_config_views
    view.dispatch('on_config_updated', config)
  File "kivy/_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-JdAJot/kivy/kivy/_event.c:7699)
  File "/home/stieg/Devel/asl/app/autosportlabs/racecapture/views/configuration/baseconfigview.py", line 122, in on_config_updated
    accordion_item.editor.on_config_updated(channel_config, max_sample_rate)
  File "/home/stieg/Devel/asl/app/autosportlabs/racecapture/views/configuration/rcp/analogchannelsview.py", line 78, in on_config_updated
    self.ids.sr.setValue(channelConfig.sampleRate, max_sample_rate)
  File "/home/stieg/Devel/asl/app/samplerateview.py", line 22, in setValue
    self.set_max_rate(max_rate)
  File "/home/stieg/Devel/asl/app/samplerateview.py", line 30, in set_max_rate
    kvFind(self, 'rcid', 'sampleRate').set_max_rate(max)
  File "/home/stieg/Devel/asl/app/sampleratespinner.py", line 13, in set_max_rate
    self.setValueMap(rates, 'Disabled')
  File "/home/stieg/Devel/asl/app/mappedspinner.py", line 36, in setValueMap
    self.text = defaultValue
  File "kivy/properties.pyx", line 408, in kivy.properties.Property.__set__ (/tmp/pip-build-JdAJot/kivy/kivy/properties.c:5114)
  File "kivy/properties.pyx", line 446, in kivy.properties.Property.set (/tmp/pip-build-JdAJot/kivy/kivy/properties.c:5876)
  File "kivy/properties.pyx", line 501, in kivy.properties.Property.dispatch (/tmp/pip-build-JdAJot/kivy/kivy/properties.c:6557)
  File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (/tmp/pip-build-JdAJot/kivy/kivy/_event.c:13497)
  File "kivy/_event.pyx", line 1106, in kivy._event.EventObservers._dispatch (/tmp/pip-build-JdAJot/kivy/kivy/_event.c:12301)
  File "/home/stieg/Devel/asl/app/fedora_env/lib/python2.7/site-packages/kivy/lang.py", line 1557, in custom_callback
    exec(__kvlang__.co_value, idmap)
  File "samplerateview.kv", line 10, in <module>
    on_text: root.onSelect(*args)
  File "/home/stieg/Devel/asl/app/samplerateview.py", line 27, in onSelect
    self.dispatch('on_sample_rate', int(selectedValue) if selectedValue is not None else 0)
  File "kivy/_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-JdAJot/kivy/kivy/_event.c:7654)
  File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (/tmp/pip-build-JdAJot/kivy/kivy/_event.c:13497)
  File "kivy/_event.pyx", line 1148, in kivy._event.EventObservers._dispatch (/tmp/pip-build-JdAJot/kivy/kivy/_event.c:13023)
  File "/home/stieg/Devel/asl/app/autosportlabs/racecapture/views/configuration/baseconfigview.py", line 37, in on_sample_rate
    self.dispatch('on_modified', self.channelConfig)
  File "kivy/_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (/tmp/pip-build-JdAJot/kivy/kivy/_event.c:7654)
  File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (/tmp/pip-build-JdAJot/kivy/kivy/_event.c:13497)
  File "kivy/_event.pyx", line 1148, in kivy._event.EventObservers._dispatch (/tmp/pip-build-JdAJot/kivy/kivy/_event.c:13023)
  File "/home/stieg/Devel/asl/app/autosportlabs/racecapture/views/configuration/baseconfigview.py", line 129, in on_modified
    self.setAccordionItemTitle(self._accordion, self.config.channels, channel_config)
  File "/home/stieg/Devel/asl/app/autosportlabs/racecapture/views/configuration/baseconfigview.py", line 133, in setAccordionItemTitle
    i = channel_configs.index(config)
ValueError: <autosportlabs.racecapture.config.rcpconfig.AnalogChannel object at 0x7fa2b7c76790> is not in list
```

**Comment by stieg** [comment]
I'm hitting this every time I try to select a different refresh rate for the battery field.

**Comment by stieg** [comment]
top of tree 1.7.0 app with 2.10.0 top of tree

**Comment by brentpicasso** [comment]
This seems to show up on MK2 as well.

**Comment by ryandoherty** [comment]
I'm not able to reproduce, anyone have a video or more details? I must be missing something.

**Comment by brentpicasso** [comment]
STR:

minicom -> resetConfig
app: read config
config / analog sensors - change a sample rate from disabled to 10Hz
write config
read config
observe error at command line

**Comment by ryandoherty** [comment]
Mk2 or RCT?

**Comment by ryandoherty** [comment]
Oops nvm, RIH.

**Comment by ryandoherty** [comment]
So according to my manual git-bisecting, commit bd993423e002e29c147b2223c344d41a7f6d8798 is when this bug first started occurring, but I can't see how it's possible. But if I test a previous commit, this bug does not occur. Can someone else verify this?

**Comment by brentpicasso** [comment]
@ryandoherty  there's something special with the last analog channel (Battery). The mismatch only happens for that item when read the 2nd time. 

To observe the effect, try putting this line before line 133 in baseconfigview.py

print(str(config) + ' xx ' + str(config.name) + ' ::: ' + str(channel_configs))

Note the object IDs matching for all of the channels except for the Battery one. 

Could this be due to anything related to RCT support?
