### ISSUE TITLE
If re-connect occurs while in dashboard mode, error with session recorder

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture_App#1130]
STR:

Connect to RCT/RCP
Navigate to dashboard
unplug / replug RCT/RCP
Observe:

08-17 15:35:29.985  5545  5561 I python  : [CRITICAL          ] [CrashHandler] Caught exception in Kivy loop: sample.session_id may not be NULL
08-17 15:35:29.987  5545  5561 I python  : [CRITICAL          ] [Traceback (most recent call last)]
08-17 15:35:29.987  5545  5561 I python  :   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 403, in mainloop
08-17 15:35:29.987  5545  5561 I python  :   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 290, in _mainloop
08-17 15:35:29.987  5545  5561 I python  :   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 327, in idle
08-17 15:35:29.987  5545  5561 I python  :   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/clock.py", line 515, in tick
08-17 15:35:29.987  5545  5561 I python  :   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/clock.py", line 647, in _process_events
08-17 15:35:29.987  5545  5561 I python  :   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/clock.py", line 406, in tick
08-17 15:35:29.987  5545  5561 I python  :   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/app/autosportlabs/racecapture/databus/databus.py", line 117, in notify_listeners
08-17 15:35:29.987  5545  5561 I python  :   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/app/autosportlabs/racecapture/data/sessionrecorder.py", line 149, in _on_sample
08-17 15:35:29.987  5545  5561 I python  :   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/app/autosportlabs/racecapture/data/sessionrecorder.py", line 131, in _save_sample
08-17 15:35:29.987  5545  5561 I python  :   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/app/autosportlabs/racecapture/datastore/datastore.py", line 472, in insert_sample
08-17 15:35:29.987  5545  5561 I python  : IntegrityError: sample.session_id may not be NULL

**Comment by brentpicasso** [comment]
this looks like a race condition where the session recorder receives samples between when it disconnects and connects
