### ISSUE TITLE
InvalidAddressException: XXX is not a valid IP address

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture_App#1163]
When trying to connect to my RCP over WiFi when I was previously using Serial I see the following:

```
[DEBUG             ] [RCPAPI      ] Starting auto-detect
[INFO              ] [SocketConnection] listening for RC wifi...
[DEBUG             ] [RCPAPI      ] Port not open...
[INFO              ] [Base        ] Leaving application in progress...
[DEBUG             ] [RCPAPI      ] Stopping msg rx worker
[INFO              ] [RCPAPI      ] cmd_sequence_worker exiting
[INFO              ] [RCPAPI      ] msg_rx_worker exiting
[INFO              ] [SocketConnection] found no RC wifi (timeout listening for UDP beacon)
[INFO              ] [RCPAPI      ] trying last known device first: /dev/ttyACM1
[DEBUG             ] [RCPAPI      ] Searching for device
[DEBUG             ] [RCPAPI      ] Trying /dev/ttyACM1
[INFO              ] [SocketComm  ] connection process starting
[DEBUG             ] [RCPAPI      ] Tx: {"getVer":null}
[ERROR             ] [SocketComm  ] Exception setting up connection thread: <class 'autosportlabs.comms.socket.socketconnection.InvalidAddressException'>/dev/ttyACM1 is not a valid IP address
[DEBUG             ] [Traceback (most recent call last)]
  File "/home/stieg/Devel/asl/app/autosportlabs/comms/socket/socketcomm.py", line 211, in _connection_message_thread
    connection.open(address)
  File "/home/stieg/Devel/asl/app/autosportlabs/comms/socket/socketconnection.py", line 87, in open
    raise InvalidAddressException("{} is not a valid IP address".format(address))
InvalidAddressException: /dev/ttyACM1 is not a valid IP address
```

Looks like our last saved path isn't an valid IP address :P.  Imagine that.  We need some form of isolation when it comes to checking the last valid point since we have many different interface types.  Each should have their own last valid point.

**Comment by ryandoherty** [comment]
This is actually intended, that is our custom exception being thrown and caught that is then logged in debug mode. The app is catching the exception, which is fine.

See https://github.com/autosportlabs/RaceCapture_App/commit/87e16e8e8a00a7e9259ce4888cc391f502fc89b6
