### ISSUE TITLE
AttributeError: 'LineChart' object has no attribute 'x_axis_value_label'

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture_App#1231]
[CRITICAL] [CrashHandler] Caught exception in Kivy loop: 'LineChart' object has no attribute 'x_axis_value_label'
[CRITICAL] [Traceback (most recent call last)]
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 619, in mainloop
    self._mainloop()
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 403, in _mainloop
    x, y = self._fix_mouse_pos(x, y)
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_sdl2.py", line 358, in _fix_mouse_pos
    self.mouse_pos = x, self.system_size[1] - y
  File "kivy/properties.pyx", line 408, in kivy.properties.Property.__set__ (/tmp/pip-build-9aBK9m/kivy/kivy/properties.c:4968)
  File "kivy/properties.pyx", line 446, in kivy.properties.Property.set (/tmp/pip-build-9aBK9m/kivy/kivy/properties.c:5666)
  File "kivy/properties.pyx", line 501, in kivy.properties.Property.dispatch (/tmp/pip-build-9aBK9m/kivy/kivy/properties.c:6315)
  File "kivy/_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (/tmp/pip-build-9aBK9m/kivy/kivy/_event.c:12786)
  File "kivy/_event.pyx", line 1130, in kivy._event.EventObservers._dispatch (/tmp/pip-build-9aBK9m/kivy/kivy/_event.c:12085)
  File "/home/brent/git-projects/RaceCapture_App/autosportlabs/racecapture/views/analysis/linechart.py", line 302, in on_mouse_pos
    self._dispatch_marker(pos[0] * self.metrics_base.density, pos[1] * self.metrics_base.density)
  File "/home/brent/git-projects/RaceCapture_App/autosportlabs/racecapture/views/analysis/linechart.py", line 243, in _dispatch_marker
    self._update_x_marker_value()
  File "/home/brent/git-projects/RaceCapture_App/autosportlabs/racecapture/views/analysis/linechart.py", line 225, in _update_x_marker_value
    self.x_axis_value_label.text = LineChartMode.format_value(self.line_chart_mode, marker_x)
AttributeError: 'LineChart' object has no attribute 'x_axis_value_label'

**Comment by brentpicasso** [comment]
Looks like there's a race condition where x_axis_value_label can be accessed before initialization.  Hard to reproduce, but caught the stack here.
