### ISSUE TITLE
"Duplicate column name" causing app to die during _extend_datalog_channels on loading .log

### ISSUE THREAD

**Issue by pugwonk** [autosportlabs/RaceCapture_App#1338]
I'm getting this:

```
 Exception in thread Thread-10:
 Traceback (most recent call last):
   File "C:\Python27\lib\threading.py", line 801, in __bootstrap_inner
     self.run()
   File "C:\Python27\lib\threading.py", line 754, in run
     self.__target(*self.__args, **self.__kwargs)
   File "C:\Users\Chris\Documents\GitHub\RaceCapture_App\autosportlabs\racecapture\views\analysis\addstreamview.py", line 320, in _loader_thread
     session_id = self.datastore.import_datalog(logpath, session_name, session_notes, self._update_progress)
   File "C:\Users\Chris\Documents\GitHub\RaceCapture_App\autosportlabs\racecapture\datastore\datastore.py", line 45, in wrap
     ret = f(*args)
   File "C:\Users\Chris\Documents\GitHub\RaceCapture_App\autosportlabs\racecapture\views\analysis\analysisdata.py", line 111, in import_datalog
     session_id = super(CachingAnalysisDatastore, self).import_datalog(path, name, notes, progress_cb)
   File "C:\Users\Chris\Documents\GitHub\RaceCapture_App\autosportlabs\racecapture\datastore\datastore.py", line 45, in wrap
     ret = f(*args)
   File "C:\Users\Chris\Documents\GitHub\RaceCapture_App\autosportlabs\racecapture\datastore\datastore.py", line 921, in import_datalog
     channels = self._parse_datalog_headers(header)
   File "C:\Users\Chris\Documents\GitHub\RaceCapture_App\autosportlabs\racecapture\datastore\datastore.py", line 450, in _parse_datalog_headers
     raise DatastoreException("Unable to import datalog, bad metadata: " + str(e))
 DatastoreException: Unable to import datalog, bad metadata
```

When loading the sample sonoma.log file from [here](https://www.dropbox.com/sh/o6u4kil4xdv4udb/AAAoOdszJSWQ9--WqUYz5zkya/sample%20logs?dl=0). It seems to be when parsing the "Utc" field (the second field in the log file - the first is Interval).

I may have corrupted the database somehow but I think it's unlikely (I deleted it yesterday) - my db is [here](https://www.dropbox.com/s/18bozt5nhiy5top/datastore.sq3?dl=0).

**Comment by brentpicasso** [comment]
resolved in 1.9.1 release
