### ISSUE TITLE
[CRITICAL] [CrashHandler] Caught exception in Kivy loop: cannot release un-acquired lock

### ISSUE THREAD

**Issue by brentpicasso** [autosportlabs/RaceCapture_App#1459]
Caught this little one in the act using the script view:

[CRITICAL] [CrashHandler] Caught exception in Kivy loop: cannot release un-acquired lock
[CRITICAL] [Traceback (most recent call last)]
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_pygame.py", line 403, in mainloop
    self._mainloop()
  File "/usr/local/lib/python2.7/dist-packages/kivy/core/window/window_pygame.py", line 289, in _mainloop
    EventLoop.idle()
  File "/usr/local/lib/python2.7/dist-packages/kivy/base.py", line 339, in idle
    Clock.tick()
  File "/usr/local/lib/python2.7/dist-packages/kivy/clock.py", line 581, in tick
    self._process_events()
  File "kivy/_clock.pyx", line 367, in kivy._clock.CyClockBase._process_events (/tmp/pip_build_root/kivy/kivy/_clock.c:7700)
  File "kivy/_clock.pyx", line 397, in kivy._clock.CyClockBase._process_events (/tmp/pip_build_root/kivy/kivy/_clock.c:7577)
  File "kivy/_clock.pyx", line 395, in kivy._clock.CyClockBase._process_events (/tmp/pip_build_root/kivy/kivy/_clock.c:7498)
  File "kivy/_clock.pyx", line 167, in kivy._clock.ClockEvent.tick (/tmp/pip_build_root/kivy/kivy/_clock.c:3490)
  File "/home/brent/git-projects/RaceCapture_App/autosportlabs/racecapture/views/configuration/rcp/scriptview.py", line 248, in poll_logfile
    self.rc_api.getLogfile()
  File "/home/brent/git-projects/RaceCapture_App/autosportlabs/racecapture/api/rcpapi.py", line 782, in getLogfile
    getLogfileCmd()
  File "/home/brent/git-projects/RaceCapture_App/autosportlabs/racecapture/api/rcpapi.py", line 777, in getLogfileCmd
    self.sendCommand({'getLogfile': None})
  File "/home/brent/git-projects/RaceCapture_App/autosportlabs/racecapture/api/rcpapi.py", line 438, in sendCommand
    self.sendCommandLock.release()
  File "/usr/lib/python2.7/threading.py", line 203, in release
    raise RuntimeError("cannot release un-acquired lock")
RuntimeError: cannot release un-acquired lock

**Comment by brentpicasso** [comment]
resolved by https://github.com/autosportlabs/RaceCapture_App/commit/b39a992a72bb54e19ce769688708e7570d3f3a21
