### ISSUE TITLE
Session Export fails with Error exporting: cannot convert float infinity to integer on RPi

### ISSUE THREAD

**Issue by john120283** [autosportlabs/RaceCapture_App#1592]
I received the following exception when attempting to export a session:

[ERROR  ] [Traceback (most recent call last)]
  File "autosportlabs/racecapture/views/analysis/analysisview.py", line 309, in _export_session_worker
  File "autosportlabs/racecapture/datastore/datastore.py", line 54, in wrap
  File "autosportlabs/racecapture/datastore/datastore.py", line 1293, in export_session
OverflowError: cannot convert float infinity to integer

I reviewed the data in the SQLite db, and there were 2 rows in the datapoint table that had a value of Inf in the UTC field, which caused the following code to throw an unchecked exception:

`if system_channel_indexes[index] == True:`
`     # our system channels are in long integer format`
`     value = long(record[1 + index])`

I was able to work around the issue by deleting the offending rows from the db:

`delete from datapoint where Utc =1e305 * 1e305`

I have a copy the database and logs (too big to upload here) if you would like to take a look at it for root cause analysis.

**Comment by brentpicasso** [comment]
Hi, thanks for the report. Can you upload your database and logs to https://www.file.io/ or similar service so we can repro and fix?

**Comment by john120283** [comment]
Here are the logs and db.
https://file.io/8tzron
https://file.io/wzD6Ez

It looks like 2 sessions have the Inf value in the UTC field.
Here are the session_id's and sample Id's
sample id      session_id   session name
849187         19                 09/29/18 - 1
2617252       63                 Harris Hill Road - 31

**Comment by brentpicasso** [comment]
Great. Thank you, will check it out.
