### ISSUE TITLE
Cannot stream telemetry from Samsung Galaxy Android 4.3

### ISSUE THREAD

**Issue by zkdzegede** [autosportlabs/RaceCapture_App#749]
I'm trying to use an older phone to stream via wifi + RCP app, but having issues only with that phone.

1) I was able to stream with the USB cable connected on a MAC with the mac app.

2) I ran the app on my primary phone, Asus Zenfone with 5.1, and turned off cell data and it streamed through wifi.

3) I tried on a Samsung Galaxy with 4.3 and it doesn't stream at all.

Attaching the app log from right after connecting to bluetooth

```
[Kivy        ] v1.9.0 
[Logger      ] Record log in /data/data/com.autosportlabs.racecapture/files/.kivy/logs/kivy_15-12-04_2.txt 
[Python      ] v2.7.2 (default, Aug 26 2015, 16:04:45) 
[GCC 4.8] 
[Factory     ] 173 symbols loaded 
stderr: /data/data/com.autosportlabs.racecapture/files/lib/python2.7/site-packages/kivy/core/image/img_pygame.py:13: RuntimeWarning: import cdrom: No module named cdrom 
stderr: (ImportError: No module named cdrom) 
[Image       ] Providers: img_tex, img_dds, img_gif, img_pygame (img_pil, img_ffpyplayer ignored) 
[Window      ] Provider: pygame 
[GL          ] OpenGL version <OpenGL ES 2.0 build 1.8.GOOGLENEXUS.blah@2198402> 
[GL          ] OpenGL vendor <Imagination Technologies> 
[GL          ] OpenGL renderer <PowerVR SGX 540> 
[GL          ] OpenGL parsed version: 2, 0 
[GL          ] Texture max size <2048> 
[GL          ] Texture max units <8> 
[Support     ] Android install hooks 
[Window      ] virtual keyboard not allowed, single mode, not docked 
[Text        ] Provider: pygame 
[Clipboard   ] Provider: android 
Call to deprecated function __call__ in /home/brent/git-projects/RaceCapture_App/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/utils.py line 251.Called from /home/brent/git-projects/RaceCapture_App/.buildozer/android/app/autosportlabs/widgets/filebrowser/__init__.py line 81 by <module>(). 
Call to deprecated function __call__ in /home/brent/git-projects/RaceCapture_App/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/utils.py line 251.Called from /home/brent/git-projects/RaceCapture_App/.buildozer/android/app/autosportlabs/racecapture/settings/systemsettings.py line 21 by get_default_data_dir(). 
Call to deprecated function __call__ in /home/brent/git-projects/RaceCapture_App/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/utils.py line 251.Called from /home/brent/git-projects/RaceCapture_App/.buildozer/android/app/autosportlabs/racecapture/settings/systemsettings.py line 30 by get_default_user_files_dir(). 
[GL          ] NPOT texture support is available 
[OSC         ] using <thread> for socket 
[Base        ] Start application main loop 
[Android     ] found 17 joystick 
[Android     ] create joystick <0> 
[Android     ] discard joystick <0> cause no button 
[Android     ] create joystick <1> 
[Android     ] create joystick <2> 
[Android     ] create joystick <3> 
[Android     ] create joystick <4> 
[Android     ] create joystick <5> 
[Android     ] create joystick <6> 
[Android     ] create joystick <7> 
[Android     ] create joystick <8> 
[Android     ] create joystick <9> 
[Android     ] create joystick <10> 
[Android     ] create joystick <11> 
[Android     ] create joystick <12> 
[Android     ] create joystick <13> 
[Android     ] create joystick <14> 
[Android     ] create joystick <15> 
[Android     ] create joystick <16> 
[RCPAPI      ] msg_rx_worker started 
[RCPAPI      ] Starting auto-detect 
[RCPAPI      ] Searching for device on all ports 
[RCPAPI      ] Trying RaceCapturePro 
[androidcomms] Opening connection RaceCapturePro 
[androidcomms] after open!!!!!!!!!!!!!!!! 
[RCPAPI      ] Found device version RCP_MK2 2.8.5 (s/n# xxx) on port: RaceCapturePro 
[DataBusPump ] Sample Meta is stale, requesting meta 
[RCPAPI      ] sending meta 
[DataBusPump ] DataBus Sampler Starting 
[StatusPump  ] starting 
[RCPAPI      ] auto detect finished. port=RaceCapturePro 
[RCPAPI      ] Execute Sequence begin 
[DataBusPump ] Sample Meta is stale, requesting meta 
[RCPAPI      ] sending meta 
[DataBusPump ] Async sampling detected 
[DataBusPump ] DataBus Sampler Exiting 
[CrashHandler] crash caught: Reference is 642345481d6d414ca3299cfd6b2c781f 
stderr: Traceback (most recent call last): 
stderr:   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 398, in mainloop 
stderr:   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/core/window/window_pygame.py", line 285, in _mainloop 
stderr:   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/base.py", line 327, in idle 
stderr:   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/clock.py", line 483, in tick 
stderr:   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/clock.py", line 615, in _process_events 
stderr:   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/platform/python-for-android/build/python-install/lib/python2.7/site-packages/kivy/clock.py", line 374, in tick 
stderr:   File "/home/brent/git-projects/RaceCapture_App/.buildozer/android/app/autosportlabs/racecapture/databus/databus.py", line 102, in notify_listeners 
stderr: RuntimeError: dictionary changed size during iteration 
[RCPAPI      ] Read message timeout 
[RCPAPI      ] POKE 
[RCPAPI      ] Read message timeout 
[RCPAPI      ] POKE 
[RCPAPI      ] Level 2 retry for (0) ver 
[RcpConfig   ] Config version 2.8.5 Loaded 
[RCPAPI      ] Execute Sequence complete 
[RaceCaptureApp] Current Tracks Loaded 
```

**Comment by zkdzegede** [comment]
This is the success log on my Asus Zenfone

```
[RCPAPI      ] Found device version RCP_MK2 2.8.5 (s/n# xxx) on port: RaceCapturePro 
[RCPAPI      ] sending meta 
[StatusPump  ] starting 
[TelemetryManager] start() telemetry_enabled: True cell_enabled: False 
[TelemetryManager] connection process is dead 
[TelemetryManager] starting connection 
[TelemetryConnection] connecting to: race-capture.com:8080 
[RCPAPI      ] auto detect finished. port=RaceCapturePro 
[TelemetryConnection] got connect 
[TelemetryConnection] authorized to RaceCapture/Live 
```

**Comment by zkdzegede** [comment]
I feel stupid... but I'll just leave this for other people to see...

Need to go to preferences and click "send telemetry".

A lot of the settings are on the RCP so I just kind of assumed that one was too.  Preferences are settings for the app :+1:
