### ISSUE TITLE
Increase write timeout for serial for MK1

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture_App#856]
After adding some exception chaining support I was able to find out why the comms were being reset for MK1.  Here is the exception chain:

```
[INFO              ] [2016-01-29 15|00|40.644] RCPAPI: tx: {"getStatus":null}
[ERROR             ] [2016-01-29 15|00|41.168] Comms: Exception in connection_process_message_writer caused by SerialTimeoutException('Write timeout',)
[WARNING           ] [2016-01-29 15|00|41.169] stderr: Traceback (most recent call last):
[WARNING           ] [2016-01-29 15|00|41.169] stderr:   File "/home/stieg/Devel/asl/rc_app/autosportlabs/comms/comms.py", line 34, in connection_process_message_writer
[WARNING           ] [2016-01-29 15|00|41.170] stderr:     connection.write(message)
[WARNING           ] [2016-01-29 15|00|41.170] stderr:   File "/home/stieg/Devel/asl/rc_app/autosportlabs/comms/serial/serialconnection.py", line 63, in write
[WARNING           ] [2016-01-29 15|00|41.170] stderr:     raise CommsErrorException(cause=e)
[WARNING           ] [2016-01-29 15|00|41.170] stderr: CommsErrorException: caused by SerialTimeoutException('Write timeout',)
```

So the failure is that MK1 is failing to read the message in 1 second.  This is likely due to the USB rx ISR code being not very good.  Things seem to be much happier if I increase the timeout from 1 to 2 seconds.

**Comment by stieg** [comment]
Fixed by #857
