### ISSUE TITLE
Dict changed size while iterating - analysis view, selecting laps

### ISSUE THREAD

**Issue by ryandoherty** [autosportlabs/RaceCapture_App#871]
If you click fast enough on the laps in the analysis view, you can get this error:

```[INFO   ] [Datastore   ] _query_channel_data function took 15.9418582916 ms
 Exception in thread Thread-5:
 Traceback (most recent call last):
   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
     self.run()
   File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
     self.__target(*self.__args, **self.__kwargs)
   File "/Users/rdoherty/Documents/projects/RaceCapture_App/autosportlabs/racecapture/views/analysis/analysisdata.py", line 151, in _get_channel_data_worker
     item.get_function(item)
   File "/Users/rdoherty/Documents/projects/RaceCapture_App/autosportlabs/racecapture/views/analysis/analysisdata.py", line 142, in _get_location_data
     params.callback(cache)
   File "/Users/rdoherty/Documents/projects/RaceCapture_App/autosportlabs/racecapture/views/analysis/analysisview.py", line 85, in <lambda>
     self._datastore.get_location_data(source_ref, lambda x: self.ids.analysismap.add_map_path(source_ref, x, map_path_color))
   File "/Users/rdoherty/Documents/projects/RaceCapture_App/autosportlabs/racecapture/views/analysis/analysismap.py", line 280, in add_map_path
     self.ids.track.add_path(source_key, path, color)
   File "/Users/rdoherty/Documents/projects/RaceCapture_App/autosportlabs/uix/track/trackmap.py", line 153, in add_path
     self._update_map()
   File "/Users/rdoherty/Documents/projects/RaceCapture_App/autosportlabs/uix/track/trackmap.py", line 285, in _update_map
     for key, track_path in paths.iteritems():
 RuntimeError: dictionary changed size during iteration```

**Comment by stieg** [comment]
Needs a ThreadSafeDictionary object or, if it already has one, is missing the use of the `with` method to secure the lock.
