### ISSUE TITLE
KeyError: 'y'

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture_App#892]
Saw the following error while disconnecting my RCP unit.  Running top of tree r/1.4.4
commit d5115126e026cc038fadaf7542c3a70afea693af

```
[ERROR  ] [Comms       ] Exception setting up connection process: <class 'serial.serialutil.SerialException'>[Errno 2] could not open port /dev/ttyACM0: [Errno 2] No such file or directory: '/dev/ttyACM0'
 Exception in thread Thread-1:
 Traceback (most recent call last):
   File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
     self.run()
   File "/usr/lib64/python2.7/threading.py", line 766, in run
     self.__target(*self.__args, **self.__kwargs)
   File "/usr/lib64/python2.7/site-packages/kivy/input/providers/mtdev.py", line 302, in _thread_run
     process([l_points[x] for x in _changes])
   File "/usr/lib64/python2.7/site-packages/kivy/input/providers/mtdev.py", line 176, in process
     touch = MTDMotionEvent(device, tid, args)
   File "/usr/lib64/python2.7/site-packages/kivy/input/motionevent.py", line 286, in __init__
     self.depack(args)
   File "/usr/lib64/python2.7/site-packages/kivy/input/providers/mtdev.py", line 50, in depack
     self.sy = args['y']
 KeyError: 'y'
```

**Comment by brentpicasso** [comment]
@stieg  does this still reproduce?

**Comment by stieg** [comment]
Haven't seen it in a while.  Will close for now.  If I see it again I will reopen.
