### ISSUE TITLE
Spaces in channel names break analysis view

### ISSUE THREAD

**Issue by stieg** [autosportlabs/RaceCapture_App#901]
Hit this issue while investigating a customer issue reported on the forums: https://autosportlabs.org/viewtopic.php?t=4717&start=0

```
[INFO              ] [DataStore   ] Created session with ID: 1
 Exception in thread Thread-8:
 Traceback (most recent call last):
   File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
     self.run()
   File "/usr/lib64/python2.7/threading.py", line 766, in run
     self.__target(*self.__args, **self.__kwargs)
   File "/home/stieg/Devel/asl/rc_app/autosportlabs/racecapture/views/analysis/addstreamview.py", line 183, in _loader_thread
     session_id = self.datastore.import_datalog(logpath, session_name, session_notes, self._update_progress)
   File "/home/stieg/Devel/asl/rc_app/autosportlabs/racecapture/datastore/datastore.py", line 23, in wrap
     ret = f(*args)
   File "/home/stieg/Devel/asl/rc_app/autosportlabs/racecapture/datastore/datastore.py", line 797, in import_datalog
     self._handle_data(dl, headers, session_id, warnings, progress_cb)
   File "/home/stieg/Devel/asl/rc_app/autosportlabs/racecapture/datastore/datastore.py", line 681, in _handle_data
     cur.executemany(datapoint_sql, datapoint_iter(newdata_gen, starting_datalog_id))
 OperationalError: near "Shock": syntax error
```

**Comment by stieg** [comment]
Attached log file this was reproduced with...
[RC_7.LOG.zip](https://github.com/autosportlabs/RaceCapture_App/files/173929/RC_7.LOG.zip)

**Comment by stieg** [comment]
The issue is triggered by a space in a quoted channel name.  In this case the channel name is `"RF Shock"`.  Workaround is to replace the space with an underscore.

**Comment by Jeff-Ciesielski** [comment]
:( no bueno.  Not that this is some sort of huge security hole or anything, but it probably wouldn't hurt to just sanitize all database inputs and document the behavior.

**Comment by ryandoherty** [comment]
IMHO this is a security issue because if someone sends out a malicious 'log' file that can potentially destroy your local imported RC app info, that's bad.

**Comment by stieg** [comment]
Here is another example of this:

```
[INFO              ] [LogImportWidget] loading log: RC_8
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/stieg/Devel/asl/rc_app/autosportlabs/racecapture/datastore/datastore.py", line 382, in _parse_datalog_headers
    self._extend_datalog_channels(new_channels)
  File "/home/stieg/Devel/asl/rc_app/autosportlabs/racecapture/datastore/datastore.py", line 360, in _extend_datalog_channels
    ADD {} REAL""".format(channel.name))
OperationalError: duplicate column name: Oil
------------------------------------------------------------
 Exception in thread Thread-10:
 Traceback (most recent call last):
   File "/usr/lib64/python2.7/threading.py", line 813, in __bootstrap_inner
     self.run()
   File "/usr/lib64/python2.7/threading.py", line 766, in run
     self.__target(*self.__args, **self.__kwargs)
   File "/home/stieg/Devel/asl/rc_app/autosportlabs/racecapture/views/analysis/addstreamview.py", line 183, in _loader_thread
     session_id = self.datastore.import_datalog(logpath, session_name, session_notes, self._update_progress)
   File "/home/stieg/Devel/asl/rc_app/autosportlabs/racecapture/datastore/datastore.py", line 23, in wrap
     ret = f(*args)
   File "/home/stieg/Devel/asl/rc_app/autosportlabs/racecapture/datastore/datastore.py", line 793, in import_datalog
     headers = self._parse_datalog_headers(header)
   File "/home/stieg/Devel/asl/rc_app/autosportlabs/racecapture/datastore/datastore.py", line 389, in _parse_datalog_headers
     raise DatastoreException("Unable to import datalog, bad metadata")
 DatastoreException: Unable to import datalog, bad metadata
```

User has two separate channels.  One is "Oil Pressure", the other is "Oil Temp".
[RC_8.LOG.txt](https://github.com/autosportlabs/RaceCapture_App/files/213576/RC_8.LOG.txt)

**Comment by ryandoherty** [comment]
Moving this to 1.4.5, we should fix this soon.

**Comment by brentpicasso** [comment]
Please put in 1.4.6, 1.4.5 is already out the door in Google play.

Brent Picasso
Autosport Labs
Technology for Race and Street
